// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClUyVsMjrsP17yGwIWgcsbl7sURPbQv94',
    appId: '1:940318905942:web:eba6e8bacd3e6bf6790df7',
    messagingSenderId: '940318905942',
    projectId: 'sikhay-d1a31',
    authDomain: 'sikhay-d1a31.firebaseapp.com',
    storageBucket: 'sikhay-d1a31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM2CtPe32vOCY0hREiRr7nv672ci3ujzI',
    appId: '1:940318905942:android:fed9693086daff51790df7',
    messagingSenderId: '940318905942',
    projectId: 'sikhay-d1a31',
    storageBucket: 'sikhay-d1a31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_yalNyLesCNzgcflDqfmW6VJDcwy7j5g',
    appId: '1:940318905942:ios:b44b269680b49a33790df7',
    messagingSenderId: '940318905942',
    projectId: 'sikhay-d1a31',
    storageBucket: 'sikhay-d1a31.firebasestorage.app',
    iosBundleId: 'com.example.sikhay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_yalNyLesCNzgcflDqfmW6VJDcwy7j5g',
    appId: '1:940318905942:ios:b44b269680b49a33790df7',
    messagingSenderId: '940318905942',
    projectId: 'sikhay-d1a31',
    storageBucket: 'sikhay-d1a31.firebasestorage.app',
    iosBundleId: 'com.example.sikhay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClUyVsMjrsP17yGwIWgcsbl7sURPbQv94',
    appId: '1:940318905942:web:b75bf0d12683785c790df7',
    messagingSenderId: '940318905942',
    projectId: 'sikhay-d1a31',
    authDomain: 'sikhay-d1a31.firebaseapp.com',
    storageBucket: 'sikhay-d1a31.firebasestorage.app',
  );
}
