import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';

import 'firebase_options.dart'; // Generated by flutterfire configure

void main() async {
  // Ensure Flutter engine is initialized before Firebase
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Wrap the entire app in ProviderScope for Riverpod
  runApp(const ProviderScope(child: SikhayApp()));
}

class SikhayApp extends StatelessWidget {
  const SikhayApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sikhay',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF0D1B2A), // Deep Navy
        primaryColor: const Color(0xFF00F5D4), // Accent Teal
        
        // Apply Poppins globally
        textTheme: GoogleFonts.poppinsTextTheme(
          Theme.of(context).textTheme.apply(
            bodyColor: Colors.white,
            displayColor: Colors.white,
          ),
        ),
        
        // Default Card Styling
        cardTheme: CardThemeData(
          color: const Color(0xFF1A2D42), // Lighter Navy
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20),
          ),
        ),
      ),
      // Placeholder for your Onboarding Screen
      home: const Scaffold(
        body: Center(
          child: Text('Sikhay: Ready to Build! 🚀'),
        ),
      ), 
    );
  }
}